name: Run Docker Build
on: [push]
jobs:
  Docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Build Docker Image
        run: docker build -t soundarriya/python-dock-img .

      - name: List Docker Image
        run: docker images

      - name: Log in to Docker GitHub
        run: echo "${{secrets.PASSWORD}}" | docker login -u ${{secrets.USERNAME}} --password-stdin

      - name: Push Docker Image
        run: docker push soundarriya/python-dock-img 